kind: pipeline
name: default

steps:
- name: test
  image: alpine
  commands:
  - "pwd"
  - "env"
  - "ls"
- name: build-growi-es
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: yaamai/growi-elasticsearch
    tags: latest
    dockerfile: Dockerfile
    context: ./growi-docker-compose/elasticsearch
